apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::379461102712:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-BIATC494AWN6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::379461102712:role/UdacityFlaskDeployCBKubectlRole
      username: build        
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-04T14:25:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1673"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 10208e7d-e91f-467e-a42a-9ebb174c413f
